### ISSUE TITLE
Problem when trying to follow the install instructions

### ISSUE THREAD

**Issue by IngoRauschenberg** [useaurora/aurora#63]
Hello,

I tried to follow these instructions
https://docs.useaurora.app/getting-started/installation-1/installation-1/installation

and got a problem at the point of the UI-Installation when I have to do
=npm run build && npm run start=
I got this error reportet

```
npm run start

> aurora@0.3.0 start /srv/aurora/aurora
> next start

(node:4336) UnhandledPromiseRejectionWarning: /srv/aurora/aurora/node_modules/jest-worker/build/WorkerPool.js:25
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/aurora/aurora/node_modules/jest-worker/build/index.js:38:42)
```

Did I do something wrong?
The api seems to work since I can reach it with a normal http request at port 5000 on the host.

Hope you can help me
best regards
Ingo

**Comment by itsrennyman** [comment]
Hello!

Thank you for your issue, what's you're Node.js version?

**Comment by IngoRauschenberg** [comment]
I tried it on a debian system.
I installed nodejs from the buster-repo so it is
10.24.0~dfsg-1~deb10u1 (the package version)

This is the output from npm version
```
npm version
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
{ npm: '5.8.0',
  ares: '1.14.0',
  brotli: '1.0.7',
  cldr: '34.0',
  http_parser: '2.9.4',
  icu: '63.1',
  modules: '64',
  napi: '7',
  nghttp2: '1.41.0',
  node: '10.24.0',
  openssl: '1.1.1d',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.24.1',
  v8: '6.8.275.32-node.59',
  zlib: '1.2.11' }
```

And yes, now I see the warning on top of the output. May this be the reason why it does not work?

**Comment by IngoRauschenberg** [comment]
I tried this on a debian system, and this is the output from npm version:

```
npm version
{ api: '1.0.0',
  npm: '5.8.0',
  ares: '1.14.0',
  cldr: '29.0',
  http_parser: '2.8.1',
  icu: '57.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.11.1',
  openssl: '1.0.2l',
  tz: '2016b',
  unicode: '8.0',
  uv: '1.34.2',
  v8: '6.2.414.50',
  zlib: '1.2.8' }
```

And yes it is still only a stretch so maybe this is the problem?

**Comment by itsrennyman** [comment]
Probably is the node.js version 8 the problem, maybe you should try with a version >= 12.

The backend is working also on node 10, but the frontend has not been tested for version 10.

Then, the docker images are using node 14 as environment

Could you try with a newer version?

**Comment by IngoRauschenberg** [comment]
Yes I will try. At first the newer versions from Debian and if this fails some newer versions manually installed.
I'll let you know the results.

**Comment by itsrennyman** [comment]
Thank you!

**Comment by IngoRauschenberg** [comment]
Hi,

first try was debian buster:
```
npm version
{ aurora: '1.0.1',
  npm: '7.5.2',
  http_parser: '2.9.4',
  node: '10.24.0',
  v8: '6.8.275.32-node.59',
  uv: '1.24.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.41.0',
  napi: '7',
  openssl: '1.1.1d',
  icu: '63.1',
  unicode: '11.0',
  cldr: '34.0',
  tz: '2018e' }
```
I got again an error, but a different one.
Second try was npm and nodejs from sid:
```
npm version
(node:13745) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
{
  npm: '7.5.2',
  node: '12.21.0',
  v8: '7.8.279.23-node.45',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.17.1',
  modules: '72',
  nghttp2: '1.43.0',
  napi: '7',
  llhttp: '2.1.3',
  http_parser: '2.9.4',
  openssl: '1.1.1k',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
```
This time the ui is working and I'm trying now to figure out how I can 'hide' this behind an apache reverse proxy.
So this issue can be closed. Thanks!
